### ISSUE TITLE
MapNumber list for Print Maps tool not displaying correct mapnumbers. 

### ISSUE THREAD

**Issue by Mercertc** [ORMAPtools/MapProduction#1]
We're having a little issue with the Map Production tool, and I'm wondering if you've seen this before and know the fix.  In the last day or two, something seems to have changed with our tool, and it's not functioning properly now.

We can open a map, but when we use the Print Map tool, or the Save Page Layout Elements tool, the map name being used is some gibberish looking name we can't find in the DB anywhere.  Here's a screen capture from the Print tool
![print maps](https://cloud.githubusercontent.com/assets/25391540/22381882/413084f6-e478-11e6-9294-91246c8f7960.PNG)

**Comment by Mercertc** [comment]
After removing the add in, and reinstalling, we are now able to print, and save to page layout elements, but only by typing in the map name.  The populated list remains a list of map names that aren't ours.

**Comment by shadc** [comment]
@Mercertc , a few things to look at. 

1.	Can you confirm that the MAPINDEX_LAYER specified in your ORMAP_LayersConfig.py exists within your map document. 
2.	Can you open that MAPINDEX_LAYER specified in your ORMAP_LayersConfig.py and confirm that it does not contain any empty or null values in the MapIndex field for the Default version (or whatever version your using in the MapProduction map document)? 

Let’s start with that.

**Comment by Mercertc** [comment]
We have fixed the problem.  Turns out we had a couple of MapIndex polys with Null mapnumbers.  Once we found them and fixed them, the problem went away.

**Comment by shadc** [comment]
Closing this issue for now.  If problem persists, I will try and add some validation.
